---

- name: Setup Photoprism
  hosts: docker
  tasks: 
    - name: Create directory
      file:
        path: /root/appdata/database
        state: directory
        owner: 999
        group: 999
    - name: Restore Backup
      unarchive:
        src:  /root/database.tar.gz
        dest:  /root/appdata/database
        owner: 999
        group: 999
        remote_src: yes
    - name: Initialize containers
      community.docker.docker_compose:
        project_src: /root/homeserver-ansible/docker-compose/photoprism
        state: present

        